siteweb:
  build: siteweb
  ports :
   - "80:80"
  volumes:
   - "./siteweb/www/:/var/www/html"
  links:
   - dbmysql
phpmyadmin:
   image: corbinu/docker-phpmyadmin
   ports :
    - "8080:80"
   environment:
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=password
   links:
    - dbmysql:mysql
dbmysql:
  image: mysql:5.5
  volumes:
   - "./dbmysql/data/:/var/lib/mysql"
   - "./dbmysql/init/:/docker-entrypoint-initdb.d"
  ports:
   - "3306:3306"  
  environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=siteweb
     - MYSQL_USER=siteweb
     - MYSQL_PASSWORD=password
